name: Go Tests

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22-alpine
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...
